GET http://localhost:5000/api/values HTTP/1.1

### values/{id}
GET http://localhost:5000/api/values/3 HTTP/1.1

### login
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
	"username": "lola",
	"password": "password"
}

###
GET http://localhost:5000/api/values
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJsb2xhIiwibmJmIjoxNTYyMDY0MzU0LCJleHAiOjE1NjIxNTA3NTQsImlhdCI6MTU2MjA2NDM1NH0.un7Hk8CCyAiWD4j8Ld-StJof2XTFN1wHd7v-WsEBqpk6HoS4hBPjNgfnorddyYX3jjrhrd78TbhqHdeaWS1CkQ

###
GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJsb2xhIiwibmJmIjoxNTYyMDY0MzU0LCJleHAiOjE1NjIxNTA3NTQsImlhdCI6MTU2MjA2NDM1NH0.un7Hk8CCyAiWD4j8Ld-StJof2XTFN1wHd7v-WsEBqpk6HoS4hBPjNgfnorddyYX3jjrhrd78TbhqHdeaWS1CkQ